# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1072, 683)
        MainWindow.setStyleSheet("background-image: url(:/newPrefix/360_F_167594893_dWtiBCm2kkQGeeIGcJSGKryKItZ8XAI1.jpg);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 0, 591, 71))
        self.label_2.setStyleSheet("color: rgb(0, 0, 127);\n"
"background-image: url(:/newPrefix/6510583-fotor-bg-remover-20230805182240.png);\n"
"font: 75 22pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 200, 321, 71))
        self.label_3.setStyleSheet("background-image: url(:/newPrefix/C:/Users/support-user/Downloads/6510583-fotor-bg-remover-20230805182240.png);\n"
"color: rgb(0, 0, 127);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(430, 560, 171, 61))
        self.pushButton_8.setStyleSheet("border-radius : 80;\n"
"color: rgb(0, 0, 127);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"border : 5px solid blac;\n"
"border-color: rgb(0, 0, 127);\n"
"border-radius : 20;")
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 300, 321, 71))
        self.label_4.setStyleSheet("background-image: url(:/newPrefix/C:/Users/support-user/Downloads/6510583-fotor-bg-remover-20230805182240.png);\n"
"color: rgb(0, 0, 127);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(360, 220, 321, 41))
        self.lineEdit.setStyleSheet("background-image: url(:/newPrefix/6510583-fotor-bg-remover-20230805182240.png);")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(360, 320, 321, 41))
        self.lineEdit_2.setStyleSheet("background-image: url(:/newPrefix/6510583-fotor-bg-remover-20230805182240.png);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(360, 430, 321, 41))
        self.lineEdit_3.setAutoFillBackground(False)
        self.lineEdit_3.setStyleSheet("background-image: url(:/newPrefix/6510583-fotor-bg-remover-20230805182240.png);")
        self.lineEdit_3.setFrame(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 410, 321, 71))
        self.label_5.setStyleSheet("background-image: url(:/newPrefix/C:/Users/support-user/Downloads/6510583-fotor-bg-remover-20230805182240.png);\n"
"color: rgb(0, 0, 127);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(570, 180, 491, 461))
        self.label_6.setStyleSheet("background-image: url(:/newPrefix/9243391-fotor-bg-remover-20230831161326.png);\n"
"background-repeat: no;")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 640, 971, 61))
        self.label.setStyleSheet("background-image: url(:/newPrefix/C:/Users/support-user/Downloads/6510583-fotor-bg-remover-20230805182240.png);\n"
"color: rgb(214, 0, 0);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(24, 70, 1011, 31))
        self.label_7.setStyleSheet("background-image: url(:/newPrefix/6510583-fotor-bg-remover-20230805182240.png);\n"
"color: rgb(156, 156, 156);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 100, 1011, 31))
        self.label_8.setStyleSheet("background-image: url(:/newPrefix/6510583-fotor-bg-remover-20230805182240.png);\n"
"color: rgb(156, 156, 156);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Add New Category : -"))
        self.label_3.setText(_translate("MainWindow", "Category Name:-"))
        self.pushButton_8.setText(_translate("MainWindow", "Add"))
        self.label_4.setText(_translate("MainWindow", "Add Fields Name:-"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Enter all fields seperate by ,"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Enter all values seperate by ,"))
        self.label_5.setText(_translate("MainWindow", "Add Fields Values:-"))
        self.label_7.setText(_translate("MainWindow", "Rember that here you add new category and it\'s field so you should enter data for this fields "))
        self.label_8.setText(_translate("MainWindow", "but if you want to add more data go to add data button in previous page."))
import img_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
